"""Hyperparameter management utilities for machine learning experiments.

This module provides functions for loading and managing hyperparameters from
configuration files, including finding the most recent configurations from
hyperparameter search results.
"""

import json
import os
from pathlib import Path
from typing import Dict, Optional

def find_most_recent_config(
    observable_key: str,
    n_spins: int,
    hyperparam_results_dir: str = "hyperparam_results"
) -> Optional[str]:
    """Find the most recent best_config.json or best_config2.json for a given observable and number of spins.
    
    Searches for configuration files in the hyperparameter results directory,
    looking for the most recent timestamped directory matching the observable
    and spin count. Checks for both best_config.json and best_config2.json.
    
    Args:
        observable_key: Observable identifier (e.g., "z_basis_opt").
        n_spins: Number of spins in the system.
        hyperparam_results_dir: Root directory containing hyperparameter search results.
        
    Returns:
        Path to the most recent best_config.json or best_config2.json file, or None if not found.
    """
    obs_dir = Path(hyperparam_results_dir) / observable_key
    if not obs_dir.exists():
        return None
    
    pattern = f"n{n_spins}_*"
    matching_dirs = sorted(obs_dir.glob(pattern), reverse=True)
    
    for dir_path in matching_dirs:
        # Check for best_config2.json first (newer format), then best_config.json
        for config_name in ["best_config2.json", "best_config.json"]:
            config_path = dir_path / config_name
            if config_path.exists():
                return str(config_path)
    
    return None

def load_hyperparams_from_config(config_path: str) -> Dict:
    """Load hyperparameters from a k-fold CV config file.
    
    Extracts hyperparameters from a configuration file generated by
    hyperparameter search, including model architecture and training parameters.
    
    Args:
        config_path: Path to the configuration JSON file.
        
    Returns:
        Dictionary containing hyperparameters with keys:
            - width: Network width
            - depth: Network depth
            - act_fun: Activation function
            - dropout: Dropout rate
            - lr: Learning rate
            - batch_size: Batch size
            - n_epochs: Number of training epochs
    """
    with open(config_path, "r") as f:
        best_config = json.load(f)
    
    hp = best_config["hyperparams"]
    
    return {
        "width": hp["width"],
        "depth": hp["depth"],
        "act_fun": hp["act_fun"],
        "dropout": hp.get("dropout", 0.0),
        "lr": hp["lr"],
        "batch_size": hp.get("batch_size", 32),
        "n_epochs": hp["n_epochs"],
    }

def initialize_hyperparams(
    observable_key: str,
    n_qubits: int,
    config_paths: Optional[Dict[str, str]] = None
) -> tuple[Dict, Optional[str]]:
    """Initialize hyperparameters from config or defaults.
    
    Attempts to load hyperparameters from a configuration file. If a specific
    config path is provided for the observable, uses that. Otherwise, searches
    for the most recent config. Falls back to default values if no config found.
    
    Args:
        observable_key: Observable identifier (e.g., "z_basis_opt").
        n_qubits: Number of qubits in the system.
        config_paths: Optional dictionary mapping observable keys to config file paths.
        
    Returns:
        Tuple of (hyperparameters_dict, config_path_used).
        If no config found, returns (defaults, None).
    """
    defaults = {
        "width": 128,
        "depth": 5,
        "act_fun": "tanh",
        "dropout": 0.0,
        "lr": 1e-3,
        "n_epochs": 400,
        "batch_size": 32
    }
    
    config_path = None
    if config_paths and observable_key in config_paths:
        config_path = config_paths[observable_key]
    else:
        config_path = find_most_recent_config(observable_key, n_qubits)
    
    if config_path and os.path.exists(config_path):
        print(f"Loading hyperparams from: {config_path}")
        hp = load_hyperparams_from_config(config_path)
        print(f"  width={hp['width']}, depth={hp['depth']}, act_fun={hp['act_fun']}")
        print(f"  dropout={hp['dropout']}, lr={hp['lr']}, batch_size={hp['batch_size']}, n_epochs={hp['n_epochs']}")
        return hp, config_path
    else:
        print(f"No config found for {observable_key}, using defaults")
        return defaults, None
